### ISSUE TITLE
if I give an entry a title that consists wholly of numbers, bolt confuses title and id

### ISSUE THREAD

**Issue by 0spinboson** [bolt/core#1004]
see title. :)

**Comment by I-Valchev** [comment]
Good spot, thanks @0spinboson.

A little more explanation of what happens:

I believe your slug uses the title field, i.e. so that the slug is also numeric.

Because of the way Bolt pulls are record from the database, it confuses the numeric slug with a record Id. This happens here:

https://github.com/bolt/core/blob/b84f6342058c9984bd7f993f9a061159cfe9087d/src/Controller/Frontend/DetailController.php#L47

I cannot think of an immediate solution to this, since if we introduce further checks (e.g. if no record with such id exists, check for slug, or vice-versa), this will cause similar problems down the line.

Maybe @bobdenotter has an opinion on this?

**Comment by 0spinboson** [comment]
from the [3.7 docs](https://docs.bolt.cm/3.7/contenttypes/intro#defining-contenttypes):

> allow_numeric_slugs (optional, advanced) | By default, Bolt prefixes slugs purely numeric with the ContentType slug (e.g. entry-123 for an entry with title 123), in order to distinguish slugs from IDs. If this option is set to true, numeric slugs remain unprefixed. Care has to be taken not to use routes of the form /{contenttype}/{id} for links in templates or for fetching content!

**Comment by bobdenotter** [comment]
This setting gave me a ton of headaches in the v3 days. The problem with this is that you're _deliberately_ creating uncertainty. If you create a record named `1`, and you then request `/entry/1`, which should you get? The record with ID 1? or the one with slug 1? 

Regardless of which one you choose, it's always an assumption, so it can never be totally correct. 

I'm going to change this so Bolt will bluntly refuse numerical slugs, and then I'll also add an example of a route to the docs, so people can have a route to a page based on _another_ field, which can be numerical. 

That way it'll be explicit, and prevents the headaches of how we did it in v3.

**Comment by bobdenotter** [comment]
See proposed fix in #1012 

After merging, we should add this example to https://github.com/bolt/project/blob/master/config/routes.yaml as well.
