### ISSUE TITLE
Can't Create New Entries

### ISSUE THREAD

**Issue by technicallyerik** [bolt/core#1255]
I am unable to create new entries when grouping my content types with "show_in_menu".

(This might have been caused by the implementation of https://github.com/bolt/core/pull/1210/files)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0-rc.13
| Install type                   |  Composer install
| PHP version                 | 7.3.9
| Web server                  | Apache
| For UX/UI issues        | Safari 13.0.5

Reproduction
------------

### Specifics

1) Group all your content types in `contenttypes.yaml` using `show_in_menu: SomeGroupName`

### Expected result

1) A sub-menu would appear under each content type that says "New [Contenttype]".  
2) The "Create New" menu in the upper-right is still populated with your content types

### Actual result

1) There are no more sub-menus under each content type that say "New [Contenttype]"
2) Each content type you add `show_in_menu` to disappears in the "Create New" menu in the upper right.

Note:  It's worth noting you can still create content by manually going to the url, e.g. (http://localhost/bolt/new/blog), but there is no more visual way to get there.

**Comment by bobdenotter** [comment]
Hi @technicallyerik ,

I've only added a button in #1293 like this: 

![Screenshot 2020-04-13 at 14 09 01](https://user-images.githubusercontent.com/1833361/79119548-e50fc500-7d90-11ea-87c9-980f03564724.png)

The menu in the topbar and in the sidear are generated from the overall menu structure, and they simply don't have the 'new' links in them. I could add the, but it'd mean making that object larger. So, it was definitely not intentional that they don't show up in there, just a consequence of how it's implemented.

At the same time, i think it _kinda_ makes sense to not have them in the "new" menu at the top. People use the 'show_in_menu: false` option to prevent a long list of contenttypes in the menu, so you probably also don't want them to clutter the "new" menu. Right?

**Comment by technicallyerik** [comment]
That's fair.  I wasn't using `show_in_menu: false` to hide things as much as `show_in_menu: <group name>` to put things into groups, but this button is a good solution.
