### ISSUE TITLE
Twig collection last/first filter breaking for loops

### ISSUE THREAD

**Issue by nealmarques** [bolt/core#1371]
Dropping the following code into a twig template 👍 

```twig
{% setcontent list =  'pages' %}
{% for i in list %}   
    [
    total pages : {{list|length}}<br>
    item:{{loop.index}} <br>
    {%set temp = list|last %}
    item:{{loop.index}} <br>
    ]
{% endfor %}
```

Should loop n times where n = total number of pages
It will currently only loop once. 
setting any variable to list|last seems to set the loop pointer to the end.
setting any variable to list|first will reset the loop back to the start.

| Relevant Bolt Version | version4.0.0 RC 17
| Install type                   | Composer install 
| BC Break                     | yes/no
| PHP version                 |  7.3 
| Web server                  | Built-in

**Comment by bobdenotter** [comment]
Hi, @nealmarques 

Does it work correctly if you use `loop.first` and `loop.last` instead of `list|first` and `list|last`?

**Comment by nealmarques** [comment]
It does work correctly with loop.first and loop.last.

**Comment by bobdenotter** [comment]
Ok, glad to hear.. Then, do you feel this is still an actual bug, or something we should document better, somewhere?

**Comment by nealmarques** [comment]
I feel like it is a bug, but now I'm wondering is this perhaps a twig templating bug rather then a bolt bug?

**Comment by bobdenotter** [comment]
What's happening (i think) is that `list|last` doesn't just _return_ the last element, but also moves the internal pointer to that last item. That then causes the loop to assume it's done, because it went past the last item. 

From the viewpoint of whomever wrote that iterator, it's probably the expected behaviour, but for end-users it's - at the very least - confusing. I'm not sure if it's feasible to fix, though. 

I'll note it down to document it better, so we have something to refer to. If more people bump into it afterwards, we should see if we can make a proper fix.
