### ISSUE TITLE
get random content not working

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1596]
Fetching random records does not work as expected.

I tried 2 ways with a freshly installed RC27 clearing cache after every change in the code.

**First:**
{% setcontent random = 'pages' limit 2 printquery %}

Returns 6 pages (the max amount set in config.yaml = `listing_records: 6`) but not randomly.

Printquery
```
SELECT content FROM Bolt\Entity\Content content WHERE content.contentType = :ct0 AND content.status = :status_1 ORDER BY content.publishedAt DESC

    ct0: pages
    status_1: published
```
**Second:**

{% setcontent pages = 'pages/random/2' printquery %}

Returns 0 results

Printquery
```
     SELECT content FROM Bolt\Entity\Content content WHERE content.contentType = :ct0 AND content.status = :status_1 AND (content.id IN(SELECT content_2.id FROM Bolt\Entity\Content content_2 INNER JOIN content_2.fields fields_2 INNER JOIN fields_2.translations translations_2 WHERE JSON_EXTRACT(translations_2.value, '$[0]') = :slug_1 AND fields_2.name = :field_2)) ORDER BY content.publishedAt DESC
        ct0: pages
        slug_1: random,2
        status_1: published
        field_2: slug
```
I expected to get 2 random pages with both queries, of course :)

---

Bolt 4.0.0 RC27

**Comment by bobdenotter** [comment]
The "Random" thing is indeed broken. @I-Valchev is working on a fix for that.. 

I took a look at the `limit 2` you said isn't working. I think it does work, but it's a bit weird: 

Let's say we have: 

```
    {% setcontent random = 'pages' limit 2 printquery %}

    {{ dump(random|length) }}  => outputs "11", because there are 11 records in total. 

    {{ dump(random) }} => Dumps pagerfanta object
```
![Screenshot 2020-07-05 at 11 28 22](https://user-images.githubusercontent.com/1833361/86529656-aa5e8a00-beb2-11ea-8187-1aa2fd66d1aa.png)

Now, this is confusing, because you'd expect "2", and not however many records there are in total. What's going wrong here, is that there are actually 2 results, but they're paginated.. See here: 

```
    {% for line in random %}
<li>{{ line.id }} = {{ line|title }}</li>
    {% endfor %}

    {{ pager(random) }}
```

Will output: 

![Screenshot 2020-07-05 at 11 30 16](https://user-images.githubusercontent.com/1833361/86529689-09bc9a00-beb3-11ea-87ac-df8322fce663.png)

So, I think what's confusing is that `random.length` doesn't give what you'd expect. Instead, you were probably looking for 

```
    {{ dump(random.getCurrentPageResults) }} => hydrated objects of the current page
    {{ dump(random.getCurrentPageResults|length) }} => How many items there actually are on the current page
```

I find this far from elegant though.. I'll need to think of a way to improve this.
