### ISSUE TITLE
Singletons can be deleted

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#1848]
Singletons show the delete button and are actually deletable, see button here:
![Screen Shot 2020-09-14 at 10 58 46 PM](https://user-images.githubusercontent.com/1833020/93171671-6243bb00-f6de-11ea-955d-b4a5cdda2898.png)

Once deleted, the singleton no longer exists:
![Screen Shot 2020-09-14 at 10 59 44 PM](https://user-images.githubusercontent.com/1833020/93171786-93bc8680-f6de-11ea-85bb-173c054d4ee2.png)

However it can be created again, but since they're unique records, I don't think they should be deleted.
I think all that would be needed to avoid this, is remove the [delete] button within the singleton edit page.

Bolt v4 RC 42

**Comment by bobdenotter** [comment]
@eduardomart Thing is: if we remove the button, people will complain they can't delete the Homepage.

"Why would people want to do that, then?!" I hear you ask. I agree, but i remember vividly how in the olden PivotX days, the system would ensure there was always a Record to populate the front page. And people just would _not_ understand why the couldn't remove it, until they've created something else.. I've learned that a lot of people work like this: 

 - Install it. 
 - Remove everything.
 - Add new stuff.

If we prevent the deletion of singletons, they'll complain about it, because they don't understand why they're not allowed to do that.

**Comment by eduardomart** [comment]
Okay, that's fair but is there currently a way to set permissions per ContentType as we had in v3?

**Comment by I-Valchev** [comment]
@eduardomart Right now there is no way to set permissions in the Bolt backend. Only admins have access to the backend, and all admins have full access to all ContentTypes. It is something on the roadmap, for sure, but not with a high priority as of now.

For frontend permissions, you can use the [bolt/users](https://github.com/bolt/users) extension.

**Comment by nestordedios** [comment]
Thank you @eduardomart for bringing this up. 

Since this was proposed and answered long time ago, I'm closing this issue as a clean up process. 

Regarding the status of setting permissions per contenttype you can find related issues on the repo.
