### ISSUE TITLE
Error when using api/contents endpoint while supplying two or more id's 

### ISSUE THREAD

**Issue by sirTachyon** [bolt/core#1953]
Hi,

I've came across an error when using the api/contents endpoint (backend -> Maintenance -> API -> /api/contents Retrieves the collection of Content resources).
You can enter an id as integer in the first field (which works just fine) but also an array of id's. When you enter one (existing) id the result all the data of contenttype with the giving id (this also works). 
But when you supply two or more id's you get this error:

`"An exception occurred while executing 'SELECT b0_.id AS id_0, b0_.content_type AS content_type_1, b0_.status AS status_2, b0_.created_at AS created_at_3, b0_.modified_at AS modified_at_4, b0_.published_at AS published_at_5, b0_.depublished_at AS depublished_at_6, b0_.author_id AS author_id_7 FROM bolt_content b0_ WHERE b0_.status = ? AND b0_.content_type NOT IN (?) AND b0_.id IN (?) ORDER BY b0_.id ASC LIMIT 30' with params [\"published\", {\"blocks\":\"blocks\"}, [\"104\",\"116\"]]:\n\nNotice: Undefined offset: 2`

The curl code is:
`curl -X GET "http://127.0.0.1:8000/api/contents?id%5B%5D=104&id%5B%5D=116" -H  "accept: application/ld+json"`

The request URL:
`http://127.0.0.1:8000/api/contents?id%5B%5D=104&id%5B%5D=116`

Things I've checked:
- Both id's exists (quadrupel check this)
- Both id's are of the same contenttype (in my "blogposts")
- When the first id doesn't exists (for example 8080) the error isn't thrown. Just an empty result
- When the second id is set the error is thrown. If it doesn't exists, the error is thrown
- Made an combination of all of the above and a contenttype (in my case "blogposts") and the results are the same

Could you take a look at this? Thanks in advance.

Also, when I've done something stupid, please correct. I'm always to learn.

Tom Schutte
The Netherlands 

![2020-10-06_23h25_28](https://user-images.githubusercontent.com/32093848/95261784-476eed00-082b-11eb-90a1-e45070c85d5a.png)

**Comment by LordSimal** [comment]
Well the error seems to be caused by the following:
![image](https://user-images.githubusercontent.com/9105243/95377610-194ce400-08e3-11eb-9fde-1da590e30637.png)

This is with the API URL `/api/contents?id%5B%5D=2&id%5B%5D=3`

Now after some xdebugging I found out, that the "main reason" is the `@ApiFilter(SearchFilter::class)` in the src/Entity/Content.php

This defined SearchFilter class `vendor/api-platform/core/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php` checks if the given values are valid for the given field.
![image](https://user-images.githubusercontent.com/9105243/95378128-c45d9d80-08e3-11eb-847e-39149f7aeb36.png)

In there it finally gets to `vendor/api-platform/core/src/Bridge/Doctrine/Common/Filter/SearchFilterTrait.php` Line 163 in which there is the following if check
```
if (self::DOCTRINE_INTEGER_TYPE === $type && null !== $value && false === filter_var($value, FILTER_VALIDATE_INT)) {
  return false;
}
```

Here everything is true and therefore the function `hasValidValues` return false which bubbles back to `vendor/api-platform/core/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php` and prevents the `filterProperty` to do its thing.

But I have no idea how to tell API-Platform via Annotations in `src/Entity/Content.php` to allow arrays to be part of the filter inside an `WHERE id IN $arr` or something like that.

**Comment by bobdenotter** [comment]
Quick idea: what does it do it you give it multiple ID's like regular queries: `2||3` ?

**Comment by simongroenewolt** [comment]
I think this is a different issue.

If I edit ContentExtension to set viewlessContentTypes to [] the error goes away.

It has to do with the param for the viewlessContentTypes being handled as an associative array by the SQLParserUtils.expandListParameters()

**Comment by simongroenewolt** [comment]
I think I've found the issue, will make a pull request.

**Comment by simongroenewolt** [comment]
The reason this issue only pops up when you ask for 2 items and not when you ask for 1 is that SQLParserUtils->expandListParameters() handles arrays differently from simple values. The array-logic gets messed up by the parameter ['blocks' => 'blocks'] (that should have been ['blocks']) and only gets in the error situation when it gets into array-logic again because it is looking up 2 content items. If only one item is requested, it doesn't enter the array-logic and apparently it'll work ok in that case.

**Comment by simongroenewolt** [comment]
FYI: A workaround for this issue is to change your configuration to not have any 'viewless' content types, so change every viewless: true to false in contenttypes.yaml. Disclaimer: I think this will only change them to be 'publicly visible' to people knowing the url, and linkable in twig by a developer, but it might have other side-effects I don't know of.

**Comment by sirTachyon** [comment]
@simongroenewolt Thanks for the tip but I saw the change was made in #1960 and applied it. It works like it should so thank you very much for fixing this.
