### ISSUE TITLE
Installing an extension through composer no longer copies default config

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#2002]
Before, when we ran `composer require bolt/forms` for example, we'd get the default config the first time _only_.

But right now, it does not do it anymore. Could it be the recent changes to `composer.json` involved with the CI Improvements? @bobdenotter  @TomasVotruba

**Comment by TomasVotruba** [comment]
I think that will be caused by something else then scripts, because scripts are run only in root `composer.json` file: https://getcomposer.org/doc/articles/scripts.md#what-is-a-script-

![image](https://user-images.githubusercontent.com/924196/96142239-2d579d80-0f02-11eb-8624-99a3c81f2a3d.png)


Could you narrow down between which 2 tags was this caused?

**Comment by simongroenewolt** [comment]
Just joining with a bit of info/research, because I'm currently trying to understand more of composer myself. Sorry, lots of text.

I first checked the composer.json file from the bolt/project repository (see at the bottom for bolt/core composer.json):
`post-install-cmd` runs `php bin/console extensions:configure --with-config`, and 
`post-update-cmd` runs `php bin/console extensions:configure` (no config copy).

Now when I create a fresh project using `composer create-project bolt/project myprojectname` I notice it invokes the `--with-config`, so the post-install must have been called. (which is as expected by [the create-project description](https://getcomposer.org/doc/03-cli.md#create-project))

If I cd to the project dir and run `composer require bolt/forms` afterwards I see `php bin/console extensions:configure` without `--with-config` so the 'post-update' is ran, and not the 'post-install'. This means no config will be copied after a 'normal' composer require command.

If you then run `composer install` after requiring bolt/forms it will actually invoke `php bin/console extensions:configure --with-config`!

Reading a bit more about the composer [command-events](https://getcomposer.org/doc/articles/scripts.md#command-events) makes me think this is exactly as specified, but certainly not how I'd understand it when looking at the commands in the composer.json file, which looks like post-install-cmd is interpreted as 'after installing something'.

Finding all this out I switched to the composer.json file in bolt/core, which is a bit different. I noticed that @TomasVotruba changed the scripts for install and update with commit https://github.com/bolt/core/commit/0e651a130e2bdeb3898f13c239a6be1174f7d84a but don't see a real difference in the scripts that are being called, _except_ for the `"@auto-scripts"` parts being gone - but I cannot link that to the copying of the config file, as the extension isn't using any symfony flex functionality.

Could it be that this has worked only 'by accident' before, for example by composer installing using a composer.json that already included the dependency on bolt/forms?
