### ISSUE TITLE
show_on_dashboard has no effect in contenttypes.yaml

### ISSUE THREAD

**Issue by iamgoodbytes** [bolt/core#2025]
**bolt 4.1.2**

When changing setting `show_on_dashboard`in `config/bolt/contenttypes.yaml` the change is not picked up.
<img width="239" alt="Screenshot 2020-10-19 at 10 30 51" src="https://user-images.githubusercontent.com/3899360/96420747-2a0c2c80-11f6-11eb-8561-46b398b24c43.png">

Expected behaviour would be to not see "Entries" in the dashboard. Removing the complete entries block from the yaml file removes it in the backend.

<img width="247" alt="Screenshot 2020-10-19 at 10 31 36" src="https://user-images.githubusercontent.com/3899360/96420840-46a86480-11f6-11eb-9ab9-cd779b72f216.png">

**Comment by bobdenotter** [comment]
I've moved the issue! 

Seems like a bug, alright. :-)

**Comment by andysh-uk** [comment]
> Seems like a bug, alright

Is it? What is the use case of having a content type that isn’t in the admin menu, so you cannot add or edit entries within it?

The way I understood this option is it filters what entries are displayed on the dashboard (the list of recent entries.)

Also being pedantic, but I see the dashboard as the first page when you login to the admin panel. The admin menu is shown on every page, so I wouldn’t expect a “dashboard” option to affect every page within the admin panel, personally.

Perhaps a separate option, “show_in_admin_menu”?

**Comment by simongroenewolt** [comment]
@andysh-uk That makes sense to me. In that case this is a feature. Also, the current docs on https://docs.bolt.cm/4.0/contenttypes/intro#defining-contenttypes say for show_on_dashboard: "When set to false the ContentType will not appear in the 'Recently edited …' list on the dashboard page." This is exactly what is happening here so I'd say this bugreport should be closed as wontfix/feature. 

If someone needs an `show_in_admin_menu` that should be a (new) feature request. I can see a use case for not showing some types in the admin interface, but that might be better served by access control and roles instead of just hiding it for everyone.

**Comment by eduardomart** [comment]
Just want to point out that this seems to be working correctly in v5

**Comment by nestordedios** [comment]
Hi @iamgoodbytes ,

You might be confusing the functionality of the `show_on_dashboard` option. 

As explained on the table below on the docs https://docs.boltcms.io/5.0/contenttypes/intro#defining-contenttypes it will show or hide the Records listed in the Dashboard page but not the hide it in the Admin menu.

As already mentioned in the previous comment the `show_on_dashboard` feature seems to be working.

Currently there is no such a feature for the result you expect in Bolt.

I'm closing this issue since it seems not to be relevant anymore. As simongroenewolt mentioned, feel free to open a new issue for that feature request.
