### ISSUE TITLE
Exception or wrong saving when changing locale

### ISSUE THREAD

**Issue by prdurand** [bolt/core#2188]
Changing locale in services.yaml causes SF exception or empty fixture (undefined name, title, etc)

Details
-------

Bolt 4.1.4 and 4.1.7 (same problem before and after udpate)
Composer install 4.1.4, / composer update 4.1.7
PHP 7.4
built-in server (bin/console server:run)

Reproduction
------------
install Bolt via composer
setup bolt
login to backend, create page, enter title, save => works fine
modify service.yaml to change main locale (tried with fr and nl, same result)
clear cache, login to backend, create page, enter title, save => SF exception
error 500
Argument 1 passed to Bolt\Repository\FieldRepository::findAllBySlug() must be of the type string, null given, called in D:\_PROJETS\Regards des lieux\www\vendor\bolt\core\src\Event\Listener\ContentFillListener.php on line 95

same scenario, but with a db reset after modifying the locale in service.yaml causes no SF exception but the fixture is saved "empty" with undefined name, undefined slug, and the url of the backend adds ?edit_locale=fr to the url.
Second attempt reach the exception

**Comment by prdurand** [comment]
May be related to server, as : 
- I can't try with server:start nor symfony CLI => doesn't work on the config I use today (not at home)
- I can't try to upload this project today (same reason, maybe on next monday)
- another bolt 4.1.7 online works fine with it, it was developped on 4.1.0 (or less? can't remember) then updated to 4.1.7

**Comment by I-Valchev** [comment]
Hi @prdurand,

Following up on our Slack conversation, can you confirm that _after_ changing the locale in `services.yaml`, you also change the `locales` for the ContentType?

The first locale in a ContentType _**must**_ be the default locale.

Still, I was able to reproduce this. The thing is, up until now I've not heard of a practical use case when someone's default locale in `services.yaml` is different than the default locale for a ContentType. If there's such a use case, I agree that will be a bug. Otherwise I'd consider this a _quirk_, but not really something to bother too much about.

**Comment by prdurand** [comment]
I have removed all info about locale in contenttypes.yaml so I didn't change anything but the services.yaml

I agree you for the importance of this problem : most of the time it's not a real one. If wasn't for me until today, where I began a work without the need of localising, but knowing my client, I guess he will ask for it one day, and I would be blocked if ever I want to add an english translation, as we'll already be into a technically speaking english project, even with french contents.

**Comment by I-Valchev** [comment]
Oh, I see. Sorry, I misunderstood what the issue is originally.

You are indeed right about this, I'll mark it as a bug and we'll have to resolve it before the next release!
