### ISSUE TITLE
[5.0] Login weirdness..

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2446]
I'm a bit stumped on what's going on, and as such I don't really know how to fix it. When creating a 'create project' for 5.0, it basically uses this `bolt/core` : https://github.com/bolt/core/releases/tag/5.0.0-beta.1.2

If I install that directly, I can log on and off just fine. 

However, if I create a new project from `bolt/project`, it installs fine: 

```
composer create-project bolt/project myprojectname "^2.0" --stability=beta
cd myprojectname
bin/console bolt:setup
```

![Screenshot 2021-02-28 at 15 57 17](https://user-images.githubusercontent.com/1833361/109422896-ac470180-79dd-11eb-9db5-89c55438869b.png)

I can run `bin/console bolt:setup` and set up the first user just fine. However, it starts breaking when i'm trying to log on: 

![Screenshot 2021-02-28 at 15 52 51](https://user-images.githubusercontent.com/1833361/109422921-d39dce80-79dd-11eb-9d79-0530884569d5.png)

If i _don't_ check the 'remember me' box, i get redirected back to the login. If i _do_ check 'remember me', it gets stuck in an endless loop. 

To continue with the weirdness, there _is_ a session started. If you change the url to `bolt/about`, you get this: 

![Screenshot_2021-02-28_at_15_53_05](https://user-images.githubusercontent.com/1833361/109422983-12338900-79de-11eb-9ab8-5888dbee96a3.png)

But, as you can see on the screenshot, the "Dashboard" option is missing from the sidebar. 

This has to be caused by some discrepancy between these two files: 

 - https://github.com/bolt/core/blob/master/config/packages/security.yaml
 - https://github.com/bolt/project/blob/master/config/packages/security.yaml

However, if i make them the same, it breaks even worse. 

To continue with the weirdness, if i edit the code in `/src/Controller/Backend/DashboardController.php`, it's clear that it start going haywire here: 

```php
$this->denyAccessUnlessGranted('dashboard');
```

Digging into that, I end up in the `isGranted()` method in `vendor/symfony/security-core/Authorization/AuthorizationChecker.php`. If I add `dd($token);` just before the return, I get this: 

![Screenshot 2021-02-28 at 16 13 24](https://user-images.githubusercontent.com/1833361/109423495-ea452500-79df-11eb-9d3d-cb22f33d0162.png)

If I do the same on my `bolt/core` checkout that's working correctly, I get this instead: 

![Screenshot 2021-02-28 at 16 14 38](https://user-images.githubusercontent.com/1833361/109423534-15c80f80-79e0-11eb-8c4e-1277a75d67bb.png)

Why is one a `RememberMeToken` and the other a `PostAuthenticationGuardToken`? I have an inkling that that's where the problem lies. But how? why? Other that that the config for `bolt/core` and `bolt/project` seems pretty much in sync. 

@I-Valchev @simongroenewolt Do either of you have a clue what might be going on here?

**Comment by simongroenewolt** [comment]
I think this difference in the security.yaml config might be the reason:

bolt/core:
```
        - { path: '^%bolt.backend_url%', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/(%app_locales%)%bolt.backend_url%', roles: IS_AUTHENTICATED_FULLY }
```

vs

bolt/project:
```
        - { path: '^%bolt.backend_url%', roles: ROLE_ADMIN }
        - { path: '^/(%app_locales%)%bolt.backend_url%', roles: ROLE_ADMIN }
```

In the new auth implementation all actual permission checks are handled by the voters, so no explicit ROLE_ is mentioned, only the requirement to be logged in. It looks like the config of bolt/project still specifies ROLE_ADMIN.

If this isn't the fix I can do some debugging later this week.

**Comment by simongroenewolt** [comment]
Also this might be very relevant because of the link to the 'remember me' token:

https://symfony.com/doc/current/security.html#checking-to-see-if-a-user-is-logged-in-is-authenticated-fully
> IS_AUTHENTICATED_FULLY: This is similar to IS_AUTHENTICATED_REMEMBERED, but stronger. Users who are logged in only because of a “remember me cookie” will have IS_AUTHENTICATED_REMEMBERED but will not have IS_AUTHENTICATED_FULLY.

This means that the 'remember me' probably will not work at all as long as IS_AUTHENTICATED_REMEMBERED is required. Probably substituting it with IS_AUTHENTICATED_REMEMBERED will fix this. (I don't think I've ever used the 'remember me' functionality, so probably I didn't check this.)

**Comment by bobdenotter** [comment]
> I think this difference in the security.yaml config might be the reason:

I tried bringing the two files in sync, making that section the same. But, it then stopped working entirely, so that wasn't the solution. :-)

**Comment by simongroenewolt** [comment]
@bobdenotter I think it will probably be _part_ of the solution then ;-) I'll have a look later this week what more needs to be changed.

**Comment by I-Valchev** [comment]
@bobdenotter @simongroenewolt  The endless loop for the `remember me` option is fixed in the PR above. Thanks @simongroenewolt for the pointers!

The issue with logging in without remember me persists. It _does_ authenticate successfully, but upon the redirect it is lost, looks like it is not read correctly from the session:

![image](https://user-images.githubusercontent.com/7093518/109648996-95c6b480-7b5b-11eb-8c8d-52d2d6333eeb.png)

The last line: 
```
[2021-03-02T12:30:47.750401+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
```
Should not happen, it shouldn't set an anonymous token if it's authenticated. I couldn't find why that happens, though.. 🤔

**Comment by bobdenotter** [comment]
I've updated the bolt/project beta with Ivo's fix.. 

```
composer create-project bolt/project myprojectname "^2.0" --stability=beta
```

Gets you a working Bolt 5.0.0 beta, but with the limitations as mentioned by @ivo.

**Comment by simongroenewolt** [comment]
I started investigating a bit.
On my bolt/core checkout I have these 2 lines. The first one is in Ivo's log, the second one is missing.

> [2021-03-07T21:42:11.797819+00:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
> [2021-03-07T21:42:12.400744+00:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []

Another line that surprised me:

>  [2021-03-07T22:34:49.343436+00:00] php.INFO: User Deprecated: Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it number aware is deprecated and will be removed in Doctrine ORM 3.0. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Creating Doctrine\\ORM\\Mapping\\UnderscoreNamingStrategy without making it number aware is deprecated and will be removed in Doctrine ORM 3.0. at /Volumes/DataCaseSensitive/projects/bolttesting1/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php:62)"} []

The config is at the expected location: `naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware`

**Comment by simongroenewolt** [comment]
Ok, found something.

If I rename `nelmio_security.yaml` to `nelmio_security.yaml.disabled` I can log in. So probably a security check that's a bit to strict on the 'normal' session cookie that somehow doesn't prevent the remember-me cookie from working?

And on the `underscore_number_aware` stuff, that line is redefined (overridden) in the configs of article and redactor. (So that should be bug reports against those extensions?)

**Comment by I-Valchev** [comment]
@simongroenewolt wow great finding!! Indeed, it turns out it's te `signed_cookie` thing that breaks, because the session cookie doesn't work with the signed check (not encrypted?)

It looks like this has been a known issue for quite some time:
https://github.com/nelmio/NelmioSecurityBundle/issues/154

For now, https://github.com/bolt/project/pull/66 disables that particular section of the nelmio security configuration. If you agree, let's roll with this and fix it once we know more about it from the nelmio issue.

**Comment by bobdenotter** [comment]
Great find, @simongroenewolt 👍

**Comment by bobdenotter** [comment]
> And on the underscore_number_aware stuff, that line is redefined (overridden) in the configs of article and redactor. (So that should be bug reports against those extensions?)

This is tackled here: 

 - https://github.com/bolt/redactor/pull/18
 - https://github.com/bolt/article/pull/27
