### ISSUE TITLE
Bolt 5.1 is incompatible with Symfony 5.3

### ISSUE THREAD

**Issue by bobvandevijver** [bolt/core#3023]
The latest Bolt version is incompatible with Symfony 5.3 due to the new authenticator system. This was added with https://github.com/bolt/core/pull/3007. 

It throws the following during the composer installation scripts:

```
PHP Fatal error:  Declaration of Bolt\Security\LoginFormAuthenticator::authenticate(Symfony\Component\HttpFoundation\Request $request) must be compatible with Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface::authenticate(Symfony\Component\HttpFoundation\Request $request): Symfony\Component\Security\Http\Authenticator\Passport\PassportInterface in /var/www/website-v2-dev/vendor/bolt/core/src/Security/LoginFormAuthenticator.php on line 43
```

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.1
| Install type                                          |  Composer install 
| <abbr title="Backwards Compatibility">BC</abbr> Break | yes
| PHP version                                           | 8.0 |
| Web server                                            | Apache

**Comment by bobdenotter** [comment]
The new `LoginFormAuthenticator` uses new Symfony 5.4 functionality. We didn't think this would be problematic, because SF is fairly good in not introducing BC during minor releases.. Didn't you get SF 5.4, when running `composer update` ?

**Comment by bobvandevijver** [comment]
Newly introduced components won't work with the older versions and they have actually changed the new authenticator quite a bit in 5.4, making it incompatible with 5.3 (where it was still experimental iirc). The experimental status also allows those changes to be made, and I believe it was removed with 5.4.

I didn't get 5.4 initially due to the flex constraint still enforcing Symfony 5.3. I did already update that (so I'm already on the latest Bolt version), but I would say that Bolt needs to update its constraints to only allow Symfony 5.4.

**Comment by I-Valchev** [comment]
Hi @bobvandevijver , thanks for reporting this and providing so much context!

My understanding is that in Symfony 5.1 the new security component was experimental, but that since 5.3 it is no longer considered such, but instead the _preferable_ option between it and the old system. At least this is what I understood according to this: https://symfony.com/blog/new-in-symfony-5-3-guard-component-deprecation

I've been able to reproduce this BC change that you describe. Indeed it has to do with the return type of the `authenticate` method, which is a difference between SF 5.3 and 5.4. PR #3028 fixes this issue, by introducing the use of the deprecated `PassportInterface`. I wasn't aware that this would cause issues, sorry about that!

**Comment by bobvandevijver** [comment]
Yeah, they made it a bit hard by changing the method signatures between 5.3 and 5.4. That is also the reason that for the OIDC authentication bundle I maintain I simply choose to only support Symfony 5.4 and higher for the new v2 version (https://github.com/Drenso/symfony-oidc)... Not much more we can do about it now ;)
