### ISSUE TITLE
FR: Use Toast UI Editor for WYSIWYG/Markdown

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#340]
This was talked about in Slack: https://ui.toast.com/tui-editor/

The good thing is that it automatically gives you HTML or Markdown with whatever content you're putting in, see the example in the link, but also please note that you can switch between modes without doing anything special, just click on the [WYSIWYG] or [Markdown] buttons at the bottom left of the demo.

You can still input arbitrary HTML in Markdown and it retains it's styles, etc.

**Comment by JarJak** [comment]
Does it allow you to customize it's interface, by e.g. hiding some icons? Does it have extensions like something for LaTeX?

**Comment by bobdenotter** [comment]
Looking into this further: 

 - Converting on the fly between HTML and Markdown loses some markup. This is understandable, because markdown simply doesn't have a DOM or AST, so a one-on-one translation is impossible. Thing is, if you _offer_ it, it's just confusing if it doesn't work. 

 - The HTML variant doesn't have a "View source" option.

**Comment by bobdenotter** [comment]
Let's close this, now we have Article and Redactor
