### ISSUE TITLE
SSL certificate problem when adding test content to the database using inbuilt fixtures

### ISSUE THREAD

**Issue by drkNsubuga** [bolt/core#3522]
Details
-------

### Bug summary

An SSL error occurs when adding sample content.  

### Environment

-  Bolt v5.2
-  Install type - Composer install
- PHP version - 8.2.x 
- Web server - Built-in, version

### Steps to reproduce
Run command to add sample content to the database.
```bash
php bin/console doctrine:fixtures:load
```
### Expected result

Sample content must be added to the database.

### Actual result
An error is shown.
```bash
In CurlResponse.php line 323:                                                                  
  SSL certificate problem: certificate has expired for "https://placeholder.boltcms.io/getfiles".
```

**Comment by rixbeck** [comment]
@drkNsubuga see #3523 please

**Comment by Sander-Hub** [comment]
Hi there,

The last 2,5 years Bob was the only contributor for Bolt (with the exception of a few of his employees) and everything surrounding it.

As mentioned on the Bolt slack, Bolt was Bob's personal project which he kindly shared with the world.
Since Bob's passing we have been trying to get access to accounts related to Bolt in order to provide a modicum of support, not only for ourselves and clients but also the community. This has proven difficult as Bob is deceased. A somewhat unfortunate side effect of a world in which we use so many online accounts and have online lives.

I wasn't aware the `placeholder.boltcms.io` subdomain was activly in use (and apparently auto renewel for certain certificates does not work properly).

The certificate for `placeholder.boltcms.io` is renewed.

Regards,
