### ISSUE TITLE
Certificate expired for placeholder.boltcms.io

### ISSUE THREAD

**Issue by Roelofpieter** [bolt/core#3523]
Just wanted to let you know that the certificate for https://placeholder.boltcms.io/getfiles has expired. This gives an error when following the installation instructions. Just wanted to let you know.

**Comment by rixbeck** [comment]
@Roelofpieter if it is blocking for you set 
```
curl_options:
    verify_peer: false
```
in `config.yml`
Afaik currently we can't set the right cert, sadly...

**Comment by drkNsubuga** [comment]
> Afaik currently we can't set the right cert, sadly...

🙏 We hope the project will live on.

**Comment by rompcik** [comment]
I think a simple change in line 18 of /src/DataFixtures/ImageFetchFixtures.php from

private const URL = 'https://placeholder.boltcms.io/getfiles';

to

private const URL = 'http://placeholder.boltcms.io/getfiles';

should do the thing, since the http-Version is still serving the right files.

**Comment by Roelofpieter** [comment]
Ok, got it. Thanks for the workaround.

**Comment by Sander-Hub** [comment]
Also see https://github.com/bolt/core/issues/3522

Hi there,

The last 2,5 years Bob was the only contributor for Bolt (with the exception of a few of his employees) and everything surrounding it.

As mentioned on the Bolt slack, Bolt was Bob's personal project which he kindly shared with the world.
Since Bob's passing we have been trying to get access to accounts related to Bolt in order to provide a modicum of support, not only for ourselves and clients but also the community. This has proven difficult as Bob is deceased. A somewhat unfortunate side effect of a world in which we use so many online accounts and have online lives.

I wasn't aware the `placeholder.boltcms.io` subdomain was activly in use (and apparently auto renewel for certain certificates does not work properly).

The certificate for `placeholder.boltcms.io` is renewed.

Regards,
