### ISSUE TITLE
Make Sanitizer obey rules from `config.yml`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#564]

**Comment by I-Valchev** [comment]
Issue with implementing this:

The `Sanitiser` gets instantiated within the `getTwigValue()` method of the `Field` entity, meaning that the $config cannot be autowired to an entity. Also, the $config cannot be passed from the Content class, because by the time `getTwigValue()` is called in Twig (`{{ field.twigValue() }}`), the Content is no longer accessible.

The problem is how to pass the config to the `getTwigValue()` method, which will instantiate the Sanitiser with it.
