### ISSUE TITLE
File dropdown z-index issues

### ISSUE THREAD

**Issue by UtechtDustin** [bolt/core#778]
While opening the dropdown of a file on the file management (http://127.0.0.1:8000/bolt/filemanager/files) the dropdown is not fully visible (z-index issue).

![Bildschirmfoto vom 2019-12-06 16-17-34](https://user-images.githubusercontent.com/13292481/70333624-22dd6980-1844-11ea-9532-6d3936b9cd8e.png)

**Comment by I-Valchev** [comment]
Nice spot! I looked into this and the issue is to do with having to display the menu items on hover above `.admin__body`, which is where the content lives.
```
.admin__sidebar {
    z-index: 2;
}
```

Once this is set, there is no way to set any children of the `.admin__body` to be higher in the stacking context than anything within `.admin__sidebar`

Also, I noticed the sidebar breaks when showing the dropdown for the last row cards:
![Screenshot 2019-12-09 at 13 58 14](https://user-images.githubusercontent.com/7093518/70437527-18151580-1a8c-11ea-8190-842088c00b96.png)

Looks like we have to think a little harder how to arrange this! :)
